### PR TITLE
Update the repository to the version used for the first submission of the article

### PR DESCRIPTION
**Pull request by nim65s**

### CODE REVIEW

**Comment by nim65s** [comment]
I guess we could call it v1.0.0

**Comment by jcarpent** [comment]
I would use the same version as the pinocchio one. What do you think?

**Comment by nim65s** [comment]
that would make sense to track pinocchio's timings, but would require to release both packages simultaneously to keep a consistency. 
It would also prevent to provide a new version if some other lib benchmarked release a version that really changes its performances

**Comment by jcarpent** [comment]
then we can add v1.3.0-{a,b,c,...} to really track variations of other libs?

**Pull request merged**
